### ISSUE TITLE
Slots counter is gaar

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#100]
De slots counter geeft nu telkens 1 of 0 (terwijl er voor het exp van dasja bijvoorbeeld echt veel meer dan 1 slots openstaan)

<img width="1239" alt="Screen Shot 2022-05-14 at 14 43 33" src="https://user-images.githubusercontent.com/31310608/168426271-6eac54a3-02f9-4ea7-9b2f-e4055186337b.png">

**Comment by tymees** [comment]
Blijft zwarte magie dit, maar ik denk dat dit te verklaren is door mijn te aggressieve fix voor de andere counters. Hopelijk heb ik het nu goed.

Komt later vandaag online!

**Comment by irisopgithub** [comment]
Is nog niet helemaal goed - er staat nu bij li's exp 3 slots, maar is er maar eentje. (er zijn wel 3 uitgesloten exp)

**Comment by tymees** [comment]
Oke ik heb die counter vervangen met een compleet andere implementatie die _wel_ onafhankelijk is van de andere counters.

De vorige methode had in isolatie wel gewerkt, maar SQL is vervelend
