### ISSUE TITLE
Al eens uitgenodigd-vinkje doet het niet meer

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#101]
als ik nu uitnodigingen stuur, wordt het vinkje niet veranderd in een kruisje voor de mensen die ik al gemaild heb. jammer, want het blijkt heel handig te zijn ;-)

**Comment by tymees** [comment]
Ik lees hier twee verschillende dingen in de titel en de beshrijving; bedoel je dat er helemaal geen vinkjes meer komen (bug) of dat een bestaand vinkje niet in een kruisje wordt omgezet als je een tweede keer mailt (enhancement)?

**Comment by irisopgithub** [comment]
ik weet nooit of het een vinkje of een kruisje wordt, eerlijk gezegd. de huidige situatie op https://experimenten-admin.lab.hum.uu.nl/datamanagement/ is dat ik geen tracker heb die ik zou kunnen verwijderen voor de schooljuffen, en dat alles bij de schooljuffen een vinkje is en blijft. ik denk nu dat dat betekent dat iedereen daar al een keer gemaild was (dat zou kloppen). maar dan is de melding dus dat ik die tracker niet kan verwijderen.

**Comment by tymees** [comment]
Je zou het moeten kunnen verwijderen via datamanagement, maar die is toch meer geschreven als een cleanup tool voor een tijdje nadat het experiment is afgelopen. 

In die zin is de datamanagement module ook geschreven om die optie pas te tonen x dagen _na de laatste afspraak_ van een experiment. (x dagen is in te stellen overigens, standaard 2 maanden). 

Het is redelijk triviaal om een knopje toe te voegen op de uitnodig pagina om alle trackers te verwijderen. Het per pp te doen kan ook, maar is wel een hoop werk om dat ook maar een beetje gebruiksvriendelijk te maken. (Aangezien je bulk delete zou willen).

Maar ik heb het idee dat er een iets andere wens verschuilt hier. Zou het een idee zijn om ipv een vinkje (of i.c.m. met een vinkje) de datum te tonen dat een zeker pp is uitgenodigd? Die informatie is er gewoon al, maar wordt niet getoond

**Comment by irisopgithub** [comment]
> Je zou het moeten kunnen verwijderen via datamanagement, maar die is toch meer geschreven als een cleanup tool voor een tijdje nadat het experiment is afgelopen.
> 
> In die zin is de datamanagement module ook geschreven om die optie pas te tonen x dagen _na de laatste afspraak_ van een experiment. (x dagen is in te stellen overigens, standaard 2 maanden).

ah, ok. dan wordt die voor dat online exp nu getoond omdat daar helemaal geen tijdstippen bij horen dus? (dat online exp is natuurlijk geen exp, dat was een truuk van mij om iedereen in de database te kunnen mailen, maar dat weet het systeem niet).

> Het is redelijk triviaal om een knopje toe te voegen op de uitnodig pagina om alle trackers te verwijderen. Het per pp te doen kan ook, maar is wel een hoop werk om dat ook maar een beetje gebruiksvriendelijk te maken. (Aangezien je bulk delete zou willen).
> 
> Maar ik heb het idee dat er een iets andere wens verschuilt hier. Zou het een idee zijn om ipv een vinkje (of i.c.m. met een vinkje) de datum te tonen dat een zeker pp is uitgenodigd? Die informatie is er gewoon al, maar wordt niet getoond

oh ja, zeker! de datum dat een pp voor het laatst is uitgenodigd dan. dat is idd wat ik eigenlijk wil weten. als ik daar dan op kan sorteren, kan ik de ppn uitnodigen die nog niet uitgenodigd zijn geweest, of al wat langer geleden.

**Comment by irisopgithub** [comment]
datum & tijd

**Comment by tymees** [comment]
Zoiets?
![image](https://user-images.githubusercontent.com/7061963/168561284-c5c88b5f-c0e1-4d98-804d-c06520ababe4.png)

(Niet uitgenodigden zijn dus altijd 'ouder' dan uitgenodigden. Leek mij het meest logisch)

**Comment by irisopgithub** [comment]
ja, zo! perfect!

**Comment by tymees** [comment]
Okay, komt later vandaag online! Het kan zijn dat sommige bestaande datums niet helemaal kloppen, omdat ik blijkbaar de datum niet updatete als je nogmaals uitnodigd. Vanaf deze update doet ie dat natuurlijk wel ;)

> ah, ok. dan wordt die voor dat online exp nu getoond omdat daar helemaal geen tijdstippen bij horen dus? (dat online exp is natuurlijk geen exp, dat was een truuk van mij om iedereen in de database te kunnen mailen, maar dat weet het systeem niet).

Zo te zien, ja; ik heb de code niet geschreven om expliciet iets te doen als er geen tijdstippen zijn. Blijkbaar vat de db het dan maar op als 'toon het maar'. Het is niet moeilijk om ze dan te verbergen, maar ik vermoed dat het wel beter is om zo te houden. Als er inderdaad online experimenten komen die nooit een afspraak gaan krijgen zou dan nooit de invites weggegooid worden.
