### ISSUE TITLE
Is hotlinken toegestaan?

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#103]
Ik probeer voor het exp van Li een plaatje in de beschrijving te krijgen van waar men geen baardgroei mag hebben. Kan het zijn dat ik niet mag hotlinken? Ik heb het plaatje zowel op surfdrive als in de resources van onze eigen site geprobeerd en krijg het plaatje niet te zien. Of ben ik echt te dom om html te tiepen?

Als het een link moet zijn zou ik die graag ook in de formulering van de vraag over baardgroei willen herhalen (want mensen lezen vaak niet wat er in de beschrijving staat - een plaatje zien ze wel staan als ze erlangs scrollen, lijkt me). Maar dat gaat ook niet, wat ik daar aan html in zet wordt eruit gestript.

**Comment by tymees** [comment]
> Ik probeer voor het exp van Li een plaatje in de beschrijving te krijgen van waar men geen baardgroei mag hebben. Kan het zijn dat ik niet mag hotlinken? Ik heb het plaatje zowel op surfdrive als in de resources van onze eigen site geprobeerd en krijg het plaatje niet te zien. Of ben ik echt te dom om html te tiepen?

Op het moment worden plaatjes van een andere plek dan experimenten.lab.hum.uu.nl niet geladen per de zogenaamde _content security policy_. Dus nee, je kan geen plaatjes van andere plekken gebruiken.

Ik zal de CSP aanpassen om meer vergevend te zijn omtend plaatjes; de huidige instelling komt uit de standaard instellingen, maar voor deze app bestaat dit aanvalsvlak eigenlijk niet. 

> Als het een link moet zijn zou ik die graag ook in de formulering van de vraag over baardgroei willen herhalen (want mensen lezen vaak niet wat er in de beschrijving staat - een plaatje zien ze wel staan als ze erlangs scrollen, lijkt me). Maar dat gaat ook niet, wat ik daar aan html in zet wordt eruit gestript.

Weer een standaard beveiligins ding, standaard wordt alle HTML naast de hardcoded HTML niet 'vertrouwd'. Het moet niet moeilijk zijn om dat aan te passen

**Comment by tymees** [comment]
Beide dingen zijn aangepast in de code, komt later vandaag online

**Comment by irisopgithub** [comment]
tnx, heel fijn!
nog even ter info: surfdrive staat bljikbaar niet toe dat je plaatjes die daar staan hotlinkt, het werkt alleen met dingen die ik in de resources van onze eigen site zet.
