### ISSUE TITLE
Bestaande expleider een solisaccount geven?

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#104]
Marijn heeft nu een bestaand account met een eigen wachtwoord, dat gemigreerd is uit het oude systeem.

Wat zou er gebeuren als ik een solisaccount voor haar maak met hetzelfde emailadres? Blijven de koppelingen met haar huidige exp dan bestaan en kan ze gewoon inloggen met haar solis-wachtwoord? Of gaan er dingen stuk?

**Comment by tymees** [comment]
Er gebeurd niks. Er staat op twee plekken een guard om je tegen te houden om een nieuwe expleider aan te maken met een bestaand expleider e-mail adres.

Ik denk dat ik wel met de hand gebruikers via de achterkant omzetten naar solis accounts, maar dat is nooit getest. Ik zou het kunnen testen met Marijn's account en als dat goed gaat die functie in de app zelf zetten?

**Comment by irisopgithub** [comment]
ja, probeer maar? ik denk wel dat het een handige functie kan zijn om te hebben, zat mensen die via proefpersoon met prive-adres uiteindelijk proefleider worden met een solisaccount, en tegen die tijd zullen ze wrsch hun solisww willen gebruiken.

wat gaat er stuk als ze daarna hun solisaccount kwijtraken en toch nog als pp mee willen doen? niet zoveel denk ik, hun email zal dan geen uu-adres meer zijn en dan maken ze een nieuw account en dan merge ik die met het vorige account en wordt het weer gewoon een studenten-proefpersoonaccount ipv een proefleider-account? of wordt het dan toch een zootje?

**Comment by tymees** [comment]
Marijn's account omzetting was successvol, en die methode is nu toegevoegd aan de app. Je hebt zometeen bij in aanmerking komende leiders een mooi zonnetje in de acties tabel waarmee je accounts om kan zetten

**Comment by tymees** [comment]
En de update staat online!

**Comment by tymees** [comment]
Ja, er wordt gekeken of een email van de uni zelf is. Gmail en casema.nl zijn dat niet, dus geen zonnetje.

Het idee is dus dat het alleen getoond wordt bij accounts die bij de UU bekend zouden moeten zijn. Het gaat niet helemaal op voor NPM's, maar die horen eigenlijk ook niet aan accounts te hangen....

**Comment by irisopgithub** [comment]
Duh, logisch. Als ik even in de echte app had gekeken ipv alleen op de acceptatieserver, had ik het zo kunnen zien. Sorry!
