### ISSUE TITLE
tekst reminder-mail editbaar maken?

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#106]
rupsje nooitgenoeg: is het veel werk om ook de tekst van de reminder-mail editbaar te maken? (dat is wat marijn en li eigenlijk het liefst zouden willen volgens mij, al zijn er uiteraard ook veel andere manieren om wat ze willen voor elkaar te krijgen)

**Comment by tymees** [comment]
Om het snel te doen? Uurtje of 2 werk max.

Echter, het aantal aanpasbare mails begint dermate hoog te worden dat ik het hele verhaal mogelijk wil herschrijven naar iets generiekers. Nu begint het wel een hoop op maat gemaakte code per mail te worden... Dat duurt natuurlijk wel langer.

Natuurlijk kan ik deze week wel eerst de snelle oplossing doen, om op langere termijn te gaan kijken naar de generieke oplossing. Ligt er dus een beetje aan hoe snel Li en Marijn willen beginnen?

**Comment by irisopgithub** [comment]
li gaat nu met de hand de reminders sturen, en dat is niet heel veel werk voor haar (ze zal toch maar een paar ppn per dag hebben, en kan ook niet elke dag meten). dus het heeft geen haast. maak maar een mooie generieke oplossing als je tijd hebt!

**Comment by tymees** [comment]
Nu ik toch bezig ben, er zijn nog een e-mail die gestuurd kan worden in de context van een experiment: de 'uitgeschreven voor experiment' mail. Zou er ooit een wens kunnen gaan zijn om die aan te passen?

**Comment by irisopgithub** [comment]
ik kan geen reden bedenken. is het veel werk om die editbaar te maken? ik gok zomaar dat je helemaal niet blij gaat zijn als je het nu niet inbouwt en men het later toch opeens blijkt te willen...

**Comment by irisopgithub** [comment]
jep, die zijn allemaal nog perfect!

**Comment by tymees** [comment]
Okay! Dan is alles nu over op het nieuwe systeem (in de grote update)

**Comment by irisopgithub** [comment]
dankjewel! dan zijn we weer klaar voor blok 2 :)

**Comment by tymees** [comment]
Nouja, als we de grote update getest krijgen voor 14 november...

**Comment by irisopgithub** [comment]
ik denk dat dit nu werkt allemaal (en zoniet, dan maak ik wel een specifiekere issue aan).
