### ISSUE TITLE
NL interface toont actions niet in overzicht exp

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#107]
Haha, ik heb me echt de hele tijd af zitten vragen waarom ik me soms heel erg erger aan het experimenten-overzicht https://experimenten-admin.lab.hum.uu.nl/experiments/ en soms niet. Dat komt doordat in de NL-versie de actions niet getoond worden! en dan kun je dus niet zo veel. De EN-versie toont de actions-kolom wel.

**Comment by tymees** [comment]
Ze worden wel getoond, maar in de 'overflow'. Die zie je vervolgens door op het blauwe plusje (helemaal links) te drukken.

Dit komt doordat de totale breedte van de tabel te groot zou worden voor de pagina, wat blijkbaar in het NL een probleem is maar op EN nog net past. (Waarschijnlijk omdat de table headers wat langer zijn in NL). Probeer maar eens een experiment te maken met 'gegevensbeschermingeffectbeoordeling'* in de naam, dan verdwijnen er een hoop kolommen de overflow in in beide talen. 

Het beste wat ik nu snel kan doen is er voor zorgen dat de actions-kolom nooit in de overflow komt, wat ik nu dus heb gedaan. Maar dan verwijnen er dus wel andere kolommen voor in de plaats. De twee echte manieren om hier van af te komen zijn
1) die lijst compleet te vervangen met een andere oplossing (Zoals bv de fancylists die we voor de FETC hebben gemaakt). of 
2) minder informatie tonen in die tabel

\* Begin je nu mijn aversie voor de samengesteldewoordenliefde van de nederlandse taal te begrijpen?

**Comment by tymees** [comment]
> Aha! Interessant, ik heb echt superveel ruimte links en rechts dus dat had ik niet bedacht. (Maar ik weet, die dingen worden ontworpen door mensen die het er mooi uit willen laten zien en daar graag wat content voor opofferen).

Ehm, ja dat is een ding ja... Ik kan natuurlijk ook op die pagina even dat 'mooie' uitzetten en het de breedte laten nemen die hij kan hebben. 

Kan je nu wel alles aan jouw kant zien?

> Ik heb eigenlijk alles op die pagina wel gewoon serieus nodig om goed te kunnen werken. Maak anders van participanten overal ppn? Ik denk dat dat ook voor iemand die mij ooit vervangt of opvolgt wel een begrijpelijke afkorting moet zijn.

Ja kan, maar het grootste probleem is de experiment namen, dus dat zou een halve oplossing zijn

**Comment by irisopgithub** [comment]
de experimentnamen krijgen wel een linebreak op een gegeven moment, dus dat veld heeft wel een maximale breedte. misschien kan die wat smaller gezet worden?

bijv 
Verhalen en emotie 4: De buurman is een klootzak
krijgt een linebreak voor klootzak.

anders hoeft het voor mij niet mooi te zijn idd. ik kan alles makkelijk op m'n scherm krijgen, zowel op de drift als thuis. (thuis kan er dan zelfs nog een hele applicatie naast)

**Comment by irisopgithub** [comment]
of heb je dat nu net aangezet, die linebreak? ik zie opeens alles en geen plusje meer

**Comment by tymees** [comment]
Ja ik heb net een wijziging gedaan die de tabel ~37% meer ruimte geeft (bij maximale breedte). Dat lost het probleem grotendeels op.

Standaard is er een 'inner container' die de content limiteerd tot een breedte van ~1140 px (en witte vlakken ernaast creert). Die heb ik er uit gehaald, en dan krijg je de 'outer container' die een max breedte heeft van ~1560px. Die inner container is waar ik naar refereerde met 'dat mooie' hier:

> Ehm, ja dat is een ding ja... Ik kan natuurlijk ook op die pagina even dat 'mooie' uitzetten en het de breedte laten nemen die hij kan hebben.

**Comment by irisopgithub** [comment]
aha! ik zie het verschil nu met de andere pagina's ja. ik vind het eerlijk gezegd ook mooier om niet zoveel wit te hebben, maargoed ik zal wel geen smaak hebben. dankjewel! ook voor alle andere wijzigingen.

**Comment by tymees** [comment]
Hetzelfde trukje heb ik bv ook toegepast op de 'participanten' pagina van een experiment, daar kan je het verschil erg goed zien omdat de header nog wel in die inner container staat.

> ik vind het eerlijk gezegd ook mooier om niet zoveel wit te hebben, maargoed ik zal wel geen smaak hebben. dankjewel! 

De keus daarvoor is eigenlijk niet een ontwerp keuze, maar een toegankelijkheidskeuze. Er is een vuistregel dat je eigenlijk moet ontwerpen met een breedte van max 1200px, omdat dat de kleinste gemene deler is van desktop schermgrootte's. (Bedank, Apple hiervoor trouwens, hun 13" MacBooks zijn de kleinste gemene deler hier).

Dat witte is gewoon iets wat het _brand team_ erbij heeft bedacht om het niet zo klein te laten lijken op grotere resoluties

**Comment by irisopgithub** [comment]
oh ja ik zie het idd. fascinerend. wat is de wereld toch groot, en wat is er toch veel structuur in de wereld.
