### ISSUE TITLE
Alle geimporteerde ppn hebben een secondary emailadres (dat leeg is)

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#110]
Dit is niet erg, maar als je je importscript nog eens wilt gebruiken wel handig om te weten: alle geimporteerde ppn hebben nu een (vaak leeg) secondary emailadress. Ik ontdekte het doordat dat een verplicht veld is als je een pp edit (ben wat bouncers weg aan het werken). Je kunt het secondary emailadres dan ook deleten dus het is in de praktijk geen probleem.

**Comment by tymees** [comment]
Het import script is compleet op maat gemaakt, dus die gaat niet hergebruikt worden.

Ik kan relatief makkelijk alle lege secundaire email adresssen weghalen (en ik heb ze allemaal gecheckt of ze echt leeg zijn), als je dat wilt?

**Comment by tymees** [comment]
Ze zijn weg, maar ik denk niet dat dat heel erg veel scheelt. De traagheid komt van 3000+ rijen moeten tonen en sorteren. 

Dat kan wel slimmer gedaan worden, maar dan moet sortering e.d. allemaal op de server gebeuren. We waren al met zoiets bezig voor de FETC, maarja, tijdgebrek en urgente problemen....
