### ISSUE TITLE
pp kan zich twee keer opgeven voor mailinglist

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#114]
Dit is een beetje een raadsel voor mij, want volgens mij heb ik dit getest en kreeg ik toen de tweede keer een melding dat ik al op de lijst stond, en geen tweede entry in de database.

Iig, er is nu een pp in de database die zich twee keer heeft opgegeven, ik zie geen verschil tussen de aanmeldingen. pp nummer 3004 en 3005. Zal rond 21.45h gebeurd zijn.

Als ik op de acceptatieserver me twee keer met dezelfde mail aanmeld nu, krijg ik geen melding dat ik al op de lijst sta, maar ook geen tweede entry in de database.

**Comment by irisopgithub** [comment]
gek toch? zou het kunnen dat hij 1 van de keren er een spatie achter had getiept ofzo, die er later afgestript is? (dat op het moment van de check ze niet hetzelfde waren, maar hoe ze uiteindelijk in de database terecht kwamen wel)

ik wil wel zo'n melding hebben, dat staat wel professioneel vind ik. dus als het weinig werk is, heel graag!

**Comment by tymees** [comment]
> gek toch? zou het kunnen dat hij 1 van de keren er een spatie achter had getiept ofzo, die er later afgestript is? (dat op het moment van de check ze niet hetzelfde waren, maar hoe ze uiteindelijk in de database terecht kwamen wel)

Dat heb ik ook gecheckt, maar tijdens de check houd hier rekening mee. Beide kanten van de vergelijking worden omgezet naar lowercase en worden de spaties van weggestript.

> ik wil wel zo'n melding hebben, dat staat wel professioneel vind ik. dus als het weinig werk is, heel graag!

Done!

**Comment by irisopgithub** [comment]
weer een pp die twee keer op de maillijst staat: 3071 en 3072. identiek, voor zover ik kan zien.

**Comment by irisopgithub** [comment]
wil je nog iets bekijken aan die dubbele ppn (3071/3072 en 3004/3005)? anders haal ik er bij elk eentje weg namelijk. tnx!

**Comment by tymees** [comment]
3004/3005 kan er eentje weg, de andere moet even wachten tot donderdag. Dan heb ik de tijd om naar die te kijken, vandaag alleen vergaderingen....

**Comment by irisopgithub** [comment]
ok, ik wacht wel ff met allebei.

Misschien gerelateerd: er is een comment in het systeem (comment 1182) dat voor mij suggereert dat ppn vrij makkelijk snel twee keer achter elkaar op 'inschrijven' kunnen klikken en daardoor problemen krijgen. Ik heb ook een paar mailtjes gehad de afgelopen weken van ppn met meldingen waardoor ik dat dacht. (of misschien is het niet twee keer klikken van de pp maar dat het systeem 'hikt'.)

Ik weet niet of dit op te lossen is - in het oude systeem kwam het iig niet voor.

**Comment by irisopgithub** [comment]
Hier is nog zo'n melding, uit een mailtje dat ik kreeg van een (andere) pp:

"Even checken: heb ik mij opgegeven voor het experiment Verhalen en Emotie 4? Ik kreeg een melding dat het tijdstip al bezet was maar kon me daarna niet voor een ander tijdstip opgeven."
d.d. van de mail is 27 juni, 20.35h.
(terzijde, maar deze pp had de bevestigingsmail niet gezien omdat ze per ongeluk een ander mailadres had gebruikt dan ze had willen gebruiken, ik heb die daarna ook nog gemerged)

**Comment by irisopgithub** [comment]
ik ben bang dat dit niet goed heeft uitgepakt, krijg van tijn de volgende melding:

"Ik heb de laatste dagen van meerdere mensen gehoord dat het niet lukt om het inschrijfformulier voor het experiment te versturen. Het lijkt iets met de browser te maken te hebben, want in Firefox werkt het wel, maar in Chrome, Safari en Internet Explorer niet. Ik heb het zelf ook geprobeerd maar bij mij werkte het ook alleen in Firefox. Weet jij wat er aan de hand is?"

bij mij werkt het in chrome ook niet - dwz, er blijft eindeloos een rondgaand dingetje rondgaan in de 'schrijf je in' knop.

**Comment by irisopgithub** [comment]
krijg nu van li een gelijksoortige melding van een andere pp

**Comment by tymees** [comment]
Ik heb een hotfix online gezet die het voor alle browsers zou moeten fixen. Morgen komt 'nette' fix.

**Comment by tymees** [comment]
Achtergrond info: FF is de enige die event priority rules volgens spec heeft geimplementeerd blijkbaar, waardoor die netjes _eerst_ de submit deed en _daarna_ pas de disable van de submit knop. De rest, doet dat dus andersom....

**Comment by irisopgithub** [comment]
het werkt bij mij nog steeds niet in chrome en safari.

die achtergrond - mijn hemel! zo kan een mens toch niet werken!

**Comment by irisopgithub** [comment]
ik heb volgens mij geen nieuwe dubbele inschrijvingen meer gezien, en ook de andere issues die hier aan de orde komen hebben zich niet opnieuw voorgedaan, dus ik heb dubbele pp 3072 gedeleerd en sluit de issue, OK?

**Comment by tymees** [comment]
Fijn om te horen!

Prima dat ie gesloten is :)
