### ISSUE TITLE
Server error 500 bij aanmaken nieuwe solis-proefleider

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#118]
Ik kreeg net een server 500 error bij het aanmaken van een nieuwe solis-proefleider.

bij nog een keer proberen krijg ik de melding There already is a leader with this email address!
maar dat is niet zo (niet dat ik kan zien althans)

ik had vlak daarvoor een proefleider omgezet van locaal naar solis-account en dat lijkt wel goed gegaan te zijn.

**Comment by irisopgithub** [comment]
ik kon wel een niet-solis-account aanmaken, en die omzetten naar een solis-account. 

maar een solis-account rechtstreeks aanmaken geeft nog steeds een server 500 error, en een proefleideraccount verwijderen ook.

**Comment by tymees** [comment]
Ik ben bang dat het toch echt iets is met het specifieke solis-ID dat je probeerde, of het moment?
Het is namelijk niet echt te reproduceren. Van wat ik uit de logs kan halen lijkt het er op dat het systeem het account niet kon vinden in de LDAP.

Wel heb ik ontdekt dat de 'converteer' functie totaal verkeerde feedback geeft of het gelukt is om een account te vinden. Ik heb dus een update gedaan die fatsoenlijke feedback geeft. (Ook geeft de app nu dezelfde feedback bij het aanmaken, ipv een error)

> bij nog een keer proberen krijg ik de melding There already is a leader with this email address!
maar dat is niet zo (niet dat ik kan zien althans)

De check is een beetje raar, en door de error werd niet alles opgeruimd, dus krijg je dat... 
Zowel de check als het niet opruimen heb ik gefixt.

> en een proefleideraccount verwijderen ook.

Ironish genoeg komt die error omdat het systeem iets te gretig de proefleideraccount verwijderd. (Hij probeerd het dubbel). Ik heb een update klaar staan die een check toevoegd of de tweede delete nog nodig is. (In sommige randgevallen

**Comment by tymees** [comment]
In conclusie, ik denk dat de solis id die je wou toevoegen niet (onder dat email) in de HUM-LDAP staat

**Comment by tymees** [comment]
Ik heb nog even goed gekeken naar de automatische retry met 'uu.nl'/'students.uu.nl', en het verhaal was niet volledig blijkbaar.
Toen ik het schreef werd het missende deel door de LDAP zelf gedaan, maar nu blijkbaar dus niet meer.

Ik heb daarom ook direct dat missende er nu in gezet

**Comment by tymees** [comment]
En ik heb vergelijkbare code toegepast op het importeren (aka aanmaken proefleider accounts), waardoor het nu ook goed zou moeten gaan als je de 'verkeerde' email variant gebruikt. (Je kan de 'juiste' versie ook direct zien in het overzicht, hij neemt dat email adres over)

**Comment by irisopgithub** [comment]
fijn, tnx!

wat gebeurt er nu als een student-assistent op een gegeven moment geen student-assistent meer is? krijgt zo iemand een mail naar z'n @uu.nl-adres doorgestuurd naar z'n @students-adres, of hoe werkt dat?

**Comment by tymees** [comment]
Ik hoor net van Ben dat het @uu.nl email dan stopt met werken...

Echt geniaal ingeregeld, mensen een @uu.nl email geven, alles overzetten daarop, en dan vervolgens dat weer afnemen....

**Comment by irisopgithub** [comment]
ik was er al bang voor.
en andersom? wordt mail naar @students-adressen doorgestuurd naar het @uu-adres? ook niet zeker?

de persoon waar het nu even om gaat blijft wel SA tot het einde van het project (heb ik gecheckt), en andere SA is momenteel geen contactpersoon voor dat exp, dus er is geen acuut probleem.

maar dit moet wel even besproken worden met de informatiemanager lijkt me. ik zet het sowieso op de agenda voor de labman+BO meeting op 26 augustus om te bespreken, maar voel je vooral vrij om het eerder aan te kaarten.

**Comment by tymees** [comment]
>  en andersom? wordt mail naar @students-adressen doorgestuurd naar het @uu-adres? ook niet zeker?

Ja, dat wel. Er is maar 1 mailbox per persoon, dus als je beide rollen hebt heeft je mailbox eigenlijk dus twee adressen. 
Zelf had ik dit graag apart gehad, ik heb me mateloos geergerd aan studenten mail tussen werk mail door :P

> de persoon waar het nu even om gaat blijft wel SA tot het einde van het project (heb ik gecheckt), en andere SA is momenteel geen contactpersoon voor dat exp, dus er is geen acuut probleem.

_Als het goed is_ update de app deze gegevens bij elke login, dus het _zou_ automatisch moeten switchen. Niet dat ik dit kan testen....

> maar dit moet wel even besproken worden met de informatiemanager lijkt me. ik zet het sowieso op de agenda voor de labman+BO meeting op 26 augustus om te bespreken, maar voel je vooral vrij om het eerder aan te kaarten.

Labman+BO meeting op 26 augustus?

En ik heb het gevoel dat onze aardige informatiemanager niet zoveel kan doen hier, ik merk dat ITS echt een heel raar beleid* voert rond dingen (ze snappen hele usecases gewoonweg niet, zelfs al geef je ze 3 A4tjes).

\* Aan de ene kant enorm inzetten op inloggen met je email, maar aan de andere kant helemaal niet snappen waarom je gegevens wilt kunnen opvragen via email bijvoorbeeld. (Ofja, dit hele uu.nl/students.uu.nl verhaal ook)

**Comment by irisopgithub** [comment]
ok, we gaan het zien, of de app de gegevens update! het gaat gegarandeerd een keer gebeuren dat een SA halverwege een exp geen SA meer is.

als het niet werkt (ongetwijfeld dan omdat ITS in de tussentijd weer iets veranderd heeft), kunnen we dus ook het solisaccount aanmaken op het uu-adres, en dan met de hand het emailadres op @students zetten, toch?

labman+ back office! 26 aug 14h. dat is de eerste keer dat ik er weer ben :)

**Comment by tymees** [comment]
> als het niet werkt (ongetwijfeld dan omdat ITS in de tussentijd weer iets veranderd heeft), kunnen we dus ook het solisaccount aanmaken op het uu-adres, en dan met de hand het emailadres op @Students zetten, toch?

Yes!

> labman+ back office! 26 aug 14h. dat is de eerste keer dat ik er weer ben :)

Oh doh, dom van me dat ik die niet door had...

**Comment by irisopgithub** [comment]
laten we deze issue vanwege verregaande ondoorgrondelijkheid van ITS ook maar sluiten voor nu...
