### ISSUE TITLE
wat is een remote id?

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#124]
ik kreeg een melding dat ik een remote id moet invoeren, hier:
https://experimenten.tst.lab.hum.uu.nl/login/

Voer een juiste remote id en wachtwoord in. Let op dat beide velden hoofdlettergevoelig zijn.

Kan daar niet gewoon emailadres staan ipv remote id?

**Comment by tymees** [comment]
Is nu gefixt!
