### ISSUE TITLE
Extra ruimte tussen vragen door info

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#125]
Bijvoorbeeld hier:
https://experimenten.tst.lab.hum.uu.nl/participant/secure/register/1/

staat veel ruimte tussen de vragen handig/dyslectisch. 
<img width="1253" alt="Screen Shot 2022-10-31 at 23 50 43" src="https://user-images.githubusercontent.com/31310608/199124618-354ff638-57b0-43a5-95d0-33ea5349c45d.png">

Ik denk dat dat komt door de info aan de rechterkant (die ik in eerste instantie niet eens gezien had). Is het niet beter om met van die mouse-over infoboxjes te werken? Oprechte vraag, ik weet niet hoe het op een telefoon eruit ziet, en ik weet dat veel ppn zich zullen inschrijven vanaf een telefoon.

**Comment by tymees** [comment]
> Ik denk dat dat komt door de info aan de rechterkant (die ik in eerste instantie niet eens gezien had).

Dat is inderdaad de oorzaak

>  Is het niet beter om met van die mouse-over infoboxjes te werken?

Dat kan, maar heeft wel wat nadelen;
Je brengt  het zelf al een beetje op met 'mouse-over' in de naam te zetten, het werkt minder goed op mobiel. Dat komt deels omdat onze huidige implementatie daarvoor niet geschikt is, maar deels is ook inherent aan dat idee op mobiel. (Een kleine hitbox recht boven een input veld kan voor irritante 'mis-touches' zorgen).

Een ander nadeel is wat indirecter; het formulier gebruikt nu ons nieuwe formulier UI (ontwikkeld voor het verwerkingsregister e.d.), dat een stuk 'vriendelijker' (zoals de UX specialist zou zeggen) overkomt dan onze oude oplossing. Nou sluit dat het gebruik van mouse-over infoboxen niet direct uit, maar we hebben simpelweg nog niks geschreven dat werkt met deze nieuwe UI. Dus dan zouden we terug moeten stappen naar de oude UI voor nu.

Nou moet ik wel zeggen dat deze helpteksten ietswat aan de lange kant zijn, waardoor deze aanpak wat minder goed uitpakt. (En ook een beetje een 'too long did not read' effect kan hebben).

>  ik weet niet hoe het op een telefoon eruit ziet

Het sprint eronder: (De margins zijn nog een beetje funky, dat klopt...)

![image](https://user-images.githubusercontent.com/7061963/199194441-b3450951-6436-47ce-a7d8-327475a133ec.png)

**Comment by irisopgithub** [comment]
Ik denk dat we die teksten er gewoon uit moeten laten, als infoboxjes niet de voorkeur heeft. Het leidt teveel af zo, vind ik. Er staat al een link naar de privacy-verklaring, dan zoeken de ppn daar maar op waarom we bepaalde vragen stellen. Misschien kunnen we bij biologisch geslacht de frase 'biologisch geslacht' ook nog een keer linken naar de privacyverklaring, dat is de meest kwetsbare vraag denk ik, het lijkt me wel goed om 'biologisch' daar te highlighten op de een of andere manier.

**Comment by irisopgithub** [comment]
ik heb hier nog steeds dezelfde mening over - die teksten in de kantlijn maken het formulier echt raar onoverzichtelijk, ik stel voor om ze eruit te halen en als volgt te vervangen:

1. direct onder de titel van het experiment in kleiner font de tekst die nu in het eerste infoboxje staat:
"Zie ook onze [privacy-verklaring](https://experimenten.tst.lab.hum.uu.nl/privacy/) voor meer informatie over waarom we deze gegevens nodig hebben en hoe wij hier mee om gaan."
2. in de vraag over biologisch geslacht, 'biologisch geslacht' linken naar de privacy-verklaring.

**Comment by irisopgithub** [comment]
in de admin-interface zijn die teksten in de kantlijn minder storend, of daar kan ik er iig wel aan wennen.

**Comment by irisopgithub** [comment]
aha! de gap-variant is veel beter, dat zal idd de/een reden zijn dat het aan de admin-kant minder stoort.

maar laten we die teksten bij het opgaveformulier er gewoon uithalen. zo inderdaad, en een anchorlink zou super zijn.

> (Dus 'Mijn [link]biologisch geslacht[/link] is')
> 
> Ik zal kijken of ik er een 'anchor-link' van kan maken, dat je direct naar dat gedeelte op de pagina wordt gestuurd als je op die link klikt
>

**Comment by tymees** [comment]
Een alternatieve layout, die de privacy verklaring verplaatst naar net boven het formulier;

Ik heb hier ook een gele balk geplaatst voor de 'inschrijf' kop, voor een betere visuele hierarchie. 

Het zijn maar suggesties ;)

![image](https://github.com/user-attachments/assets/c808b6aa-2d4d-4b9b-9aa6-95bc04dcbaa6)

**Comment by irisopgithub** [comment]
ja die laatste is beter!
