### ISSUE TITLE
Message when failed bij special criteria

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#126]
Ik kan de 'message when failed' bij de special criteria nergens zien. Ik dacht dat ik dat vroeger wel kon. Ik heb iig een voorbeeld nodig... weet even niet meer hoe ik dat deed met 'mailto' enzo.

**Comment by tymees** [comment]
Ik zie hem wel staan op de pagina waar je special criteria toevoegd?
Bijvoorbeeld:
https://experimenten-admin.lab.hum.uu.nl/experiments/284/criteria/

Het kan zijn dat hij verborgen is achter 'het blauwe plusje' als je scherm klein is

**Comment by irisopgithub** [comment]
ah yes fantastisch, bij een specifiek exp staat het wel! dankjewel!

ik zat hier te kijken: https://experimenten-admin.lab.hum.uu.nl/experiments/criteria/
zou 'm daar wel willen zien als ik een criteria ga editen.

maar voor nu gered, super, dankjewel en fijne avond!

**Comment by tymees** [comment]
Die antwoorden zijn per experiment opgeslagen*. Ik kan in principe wel alle mogelijke failed messages in die overzichtspagina zetten, maar ik denk niet dat het er echt overzichtelijker van word. Ik zou zelf dan een pagina maken waar je alle gebruiken van dat criteria kan zien, met de failed messages erbij.

Zeg maar welke van de twee opties je prefereerd :)

* Immers, het is ietswat raar als je 'sorry, voor dit experiment mag je geen bril/lensen dragen' als je 'nee' hebt geantwoord op de vraag 'heb je een bril/lensen'. Dus het leek me handiger om het dan maar per experiment aanpasbaar te maken :P

Fijne avond!

**Comment by irisopgithub** [comment]
haha, bij elke vraag die ik jou stel, heb jij een betere vraag terug! ik ga erover nadenken ;-)

**Comment by irisopgithub** [comment]
laten we het maar laten zoals het is!
