### ISSUE TITLE
html parsen in compensation field in de preview

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#128]
We moeten aan de yesty-bonnen, en ik zou graag een link willen zetten in het veld van de compensatie, maar dat ziet er dan zo uit in de preview:

<img width="1138" alt="Screenshot 2023-03-03 at 15 29 57" src="https://user-images.githubusercontent.com/31310608/222746957-1e754523-a52f-42ac-bfcf-efc3c62f1581.png">

Op de inschrijfpagina zelf ziet het er wel goed uit!

**Comment by tymees** [comment]
@bbonf could you fix this? Should be a simple fix

It's a Vue template issue, basically one should use the v-html directive for that line. (As demonstrated elsewhere in the template)

**Comment by irisopgithub** [comment]
the first instance is OK now (and so is the invitation email), but the second instance in the preview page is still unparsed: 
<img width="859" alt="Screenshot 2023-03-03 at 16 16 21" src="https://user-images.githubusercontent.com/31310608/222757751-a98f0100-22f9-456b-bee4-6234efe719d2.png">

**Comment by irisopgithub** [comment]
> @irisopgithub ~could you try again?~ sorry, missed a spot

crosspost :)

**Comment by bbonf** [comment]
should be fixed now!

**Comment by irisopgithub** [comment]
yes it's perfect, thank you so much!
