### ISSUE TITLE
Mergen van 2 pps gaat niet goed als de primaire minder gegevens heeft

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#129]
Ik heb een beetje gekke situatie:

pp had een account, met een geldig @students-mailadres. Had nooit meegedaan met exp, dus niet alle gegevens waren bekend.

pp geeft zich vervolgens op voor een exp, maar met het verkeerde emailadres, namelijk @student.uu (zonder s)

Ik merge deze twee, maar heb nu een gecombineerde pp die wel dat account heeft, maar niet alle gegevens van de tweede met het verkeerde emailadres. Het tijdstip is wel gekoppeld, en de special criteria ook, en sommige van de default criteria ook. Maar nu ontbreken: geboortedatum, handedness en sex. Die zijn dus uit de eerste pp overgenomen, op zich willen we dat ook, maar natuurlijk alleen als ze zijn ingevuld.

**Comment by irisopgithub** [comment]
Beetje in dezelfde categorie: bij het mergen van twee pps krijgt de variabele 'op mailinglist' de waarde van de oude pp, dat moet natuurlijk de waarde van de nieuwe pp zijn.

**Comment by tymees** [comment]
Whoops, deze is compleet langs me heen gegaan. Ik zal er vrijdag naar kijken

**Comment by irisopgithub** [comment]
no worries. ik zit nog steeds dingen te melden over het oude systeem (dat nog steeds in gebruik is), terwijl ik natuurlijk allang had moeten testen met de nieuwe.

**Comment by tymees** [comment]
Okay dit is een simpel probleem; die waardes werden simpelweg nooit overgezet.

Ik heb er nu een stukje code aan toegevoegd die checkt of de waarde leeg is in de 'bestaande', en zo ja, zet de waardes uit de 'nieuwe' alsnog over. (Ter verduidelijking, dit geld voor de volgende velden: 'birth_date', 'handedness', 'sex', 'dyslexic', 'multilingual')

Ook wordt de nieuwe waarde van 'op mailinglist' altijd overgenomen van de 'nieuwe'.

Ik zet het zometeen op de acceptatieserver
