### ISSUE TITLE
tekstje op nieuw-experiment-aanmaak-pagina

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#130]
(dit gaat over de nieuwe interface, die er goed uitziet trouwens en best fijn werkt)

op https://experimenten-admin.tst.lab.hum.uu.nl/experiments/new/

staat 
The main experiment leader, who will be displayed as the contact on the experiment page. 

zou je daarvan willen maken:
The main experiment leader, who will be displayed as the contact on the experiment page, and whose contact details will appear in confirmation and reminder emails to the participant.

voor het nederlands:

De hoofd-proefleider. Dit is de proefleider die getoond wordt als de contactpersoon op de experiment-pagina, en wiens contactgegevens in bevestigings- en herinneringsmails aan de proefpersoon gestuurd worden.

**Comment by irisopgithub** [comment]
op https://experimenten-admin.tst.lab.hum.uu.nl/experiments/3/criteria/ staat

Base criteria are shared between experiments, in order to make exclusion more efficient. (e.g. not inviting participants if we know they will not be able to participate). Every experiment has to specify their own 'correct answer' and 'message when failed', so you can make 'wearing glasses' mandatory in experiment X and not allowed in experiment Y.
Here you can link specific criteria to this experiment, either by creating a new criterion or by selecting an existing one. 

ik zou hiervan maken:

Base criteria are shared between experiments, in order to make exclusion more efficient. (e.g. not inviting participants if we know they will not be able to participate), and to collect demographic information that will need to be reported for every experiment upon publication (e.g. handedness, biological sex).
Here you can link specific criteria to this experiment, either by creating a new criterion or by selecting an existing one. Every experiment has to specify their own 'correct answer' and 'message when failed', so you can make 'wearing glasses' mandatory in experiment X and not allowed in experiment Y.

**Comment by tymees** [comment]
Beide teksten zijn ge-update; komt later vandaag op de testserver

**Comment by irisopgithub** [comment]
tnx!
