### ISSUE TITLE
html wordt niet geparst in deel van uitnodigingsmail

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#131]
(dit gaat over het nieuwe systeem, in het huidige systeem gaat dit wel goed). zie screenshot hieronder:

<img width="618" alt="Screenshot 2023-07-19 at 13 49 08" src="https://github.com/UiL-OTS-labs/ppn-backend/assets/31310608/8e39496f-0fa3-45bc-b074-975ae05d4ac5">

**Comment by tymees** [comment]
Ah ja; the HTML injection protection strikes again.

ik moet even kijken hoe ik dit precies ga oplossen. Idealiter kan ik per variabele die protection in de code zelf uitzetten. Op dit moment kan dat alleen voor de hele mail. (Wat niet echt een optie is, omdat we anders CERT op ons dak krijgen dat een persoon met slechte intenties dit kan misbruiken via de 'name' variabele).

Dat kan even een paar weken duren voordat ik het af en goed getest heb.

Voor nu kan dit handmatig al door in de template `|safe` toe te voegen aan de variable. (Dus bv ``{{ compensation|safe }}``).

**Comment by tymees** [comment]
Fixed!
