### ISSUE TITLE
Nieuwe menu balk?

### ISSUE THREAD

**Issue by tymees** [UiL-OTS-labs/ppn-backend#132]
ITS is een refresh voor de UU huisstijl aan het ontwerpen; aangezien ik daar vanuit PortalDev aan meewerk hebben we first-access voordelen ;)

Een van die dingen de we nu hebben ontworpen is een nieuwe header/menu balk speciaal voor interne web-apps. Het grote verschil is dat het een stuk minder verticale hoogte inneemt dan de oude.

We hoeven hem niet te gebruiken voor deze app (en voor de frontend lijkt hij me sws niet logisch, omdat dat een public-facing app is). Maar ik geef je graag de keuze of je hem wilt hebben of niet @irisopgithub; de code ervoor is (opzettelijk) bijna hetzelfde, om zo'n switch makkelijker te maken (lees: het kost niet echt veel tijd om te doen). 

Een voorbeeld:
![image](https://github.com/UiL-OTS-labs/ppn-backend/assets/7061963/40e888b8-f6ae-4ae4-bede-d02910b7efa2)

Ter vegelijking, de oude:
![image](https://github.com/UiL-OTS-labs/ppn-backend/assets/7061963/5312673b-5e28-4a73-9b79-5bfbfab7822b)

**Comment by irisopgithub** [comment]
oh ja, dat wil ik wel!

**Comment by tymees** [comment]
Dit wordt het dan:
![image](https://github.com/UiL-OTS-labs/ppn-backend/assets/7061963/f7a6216f-d1a9-4c24-a766-549271a14cc7)

Ik moet nog wat kleine dingetjes fixen eraan, maar met een beetje geluk staat het aan het eind van de dag op de testserver

**Comment by irisopgithub** [comment]
ja mooi!

**Comment by tymees** [comment]
Hij staat op de dev-server!

Mogelijk dat je je cache moet legen (ctrl+shift+r) voordat de nieuwe navbar goed werkt
