### ISSUE TITLE
hoe inactief account pp verwijderen?

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#140]
ik kom een pp tegen die met een students.uu.nl-adres een account heeft aangemaakt ooit. zich vervolgens van de mailinglist heeft uitgeschreven. en nu zich weer heeft ingeschreven, met een ander mailadres, zonder account.

ik heb haar gemerged, maar wil nu eigenlijk dat uu.nl-account van haar gewoon verwijderen (want daar wou ze geen mail meer op krijgen, en gedoe als later een andere student dat mailadres krijgt). hoe doe ik dat? ik kan het in de django-interface niet vinden.

**Comment by tymees** [comment]
Die accounts heten 'Api User' in de django-admin, daar zou je hem moeten kunnen verwijderen

**Comment by irisopgithub** [comment]
tnx, gelukt, en labwiki geupdate!
