### ISSUE TITLE
invite template

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#143]
https://experimenten-admin.tst.lab.hum.uu.nl/experiments/6/emails/

ik heb het invite template aangepast (link naar zogenaamde informatiebrief toegevoegd). dat werkt, maar. ik weet niet of het door deze aanpassing komt, of al zo was, maar nu werkt de link naar het inschrijfformulier niet, als ik daarop klik in m'n mail dan opent-ie iets html-erigs in m'n mail zelf ipv iets in de browser.

**Comment by tymees** [comment]
Huh.... Oke ik kan jouw gedrag niet her-produceren, maar ik heb wel een foutje gevonden in de standaard tekst. (De link gebruikte `ref_link` als variabele, wat `reg_link` had moeten zijn).

Ik heb dat zowel in de sjabloon voor nieuwe experimenten aangepast (nog niet live), als voor het `zomervakantie` experiment specifiek (wel live natuurlijk). 

Kan je het nog eens proberen?

**Comment by irisopgithub** [comment]
jep, nou doet-ie het wel!

**Comment by tymees** [comment]
Ik ben nu heel benieuwd wat jouw mailclient nou precies denkt te doen, maar fijn dat die typo fixen inderdaad het probleem oplost

**Comment by irisopgithub** [comment]
is gewoon thunderbird. soortgelijke bug zit in Vinted, die sturen 800000 mails over van alles en nog wat, daar zit er eentje tussen waarbij als je op de knop klikt, je niet naar de vinted-site gaat maar onbegrijpelijk html-gebrabbel in je mailbrowser krijgt.

**Comment by tymees** [comment]
Okay ik heb het nu ff getest met een thunderbird mail (ik testte zelf ff snel met gmail).

Wat er dus gebeurd in dit geval is dat hij de mail zelf opent... In plain text-mode. Dus je ziet de 'broncode' van de mail :P

Niet heel raar, gezien het probleem was dat de url leeg was (en hij dus default naar 'deze pagina'), maar wel echt super verwarrend
