### ISSUE TITLE
html wordt niet geparset op overzichtspagina

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#144]
https://experimenten.tst.lab.hum.uu.nl/
<img width="1268" alt="Screenshot 2024-07-17 at 15 31 04" src="https://github.com/user-attachments/assets/41edced1-601d-4bb3-8323-f2757ed0fc49">

**Comment by tymees** [comment]
Oke, ik heb nu maar alle invulbare velden 'HTML safe' gemaakt... Voor het geval je ook ooit HTML wilt toevoegen aan de 'duur' of de locatie. (Al in dat laatste geval kan dat.... interresante situaties veroorzaken). 

Komt begin volgende week op de testserver met de andere fixes

**Comment by irisopgithub** [comment]
locatie heeft al een veld waar een link in kan (de routebeschrijving), dus dat komt wel goed denk ik.

ik ga nu even pauze nemen, is het goed als ik vanavond nog een rondje doe met inschrijven als pp en dat we dan eind augustus verder gaan? of moet het sneller ivm de veiligheid? iris vd wulp en philine hebben ook nog ppn geboekt staan, iris nog t/m eind augustus.

**Comment by irisopgithub** [comment]
ik zou philine en iris dan even kunnen mailen dat ze voorlopig geen nieuwe tijdstippen moeten toevoegen omdat we eind augustus overgaan op een nieuwe versie (en ook omdat we niet weten wat er in september allemaal voor overlast van die kademuren gaat komen). maar als we eerder over moeten, dan moet dat natuurlijk.

**Comment by tymees** [comment]
Vooralsnog is er niks langsgekomen aan kwestbaarheden die ons forceerd snel te updaten. (Nouja, er is nog helemaal niks langsgekomen zelf). 

En zelfs als dat de komende maand gebeurd, de opzet van de app is al erg veilig. Dus ik kan uitstel wel verantwoorden als er er een haan gaat kraaien. Dus ik vind het prima om te wachten. 

(Zolang het maar niet augustus 2025 wordt)

**Comment by irisopgithub** [comment]
ok, ik heb m'n autoreply aan staan tot donderdag 29 augustus, en in m'n agenda gezet dat ik woensdag 28 augustus vrijhoud voor ppn-systeem. (en ik zal ook labwiki en howto moeten updaten)
