### ISSUE TITLE
verklarende tekst comment

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#146]
niet noodzakelijk, maar aangezien er nu toch allerlei hulp-info in de applicatie staat... 

proefleiders snappen niet altijd dat als ze een comment aanmaken over een pp, dat die dan alleen naar mij toe gaat en niet naar de pp. voorstel voor een tekstje:
https://experimenten.tst.lab.hum.uu.nl/leader/experiment/6/participants/3/add_comment/

The comment that you submit here, will only be visible to the recruitment system admin (not to the participant). You can report particularities about the participant here, for instance if they didn't show up without letting you know, or if they were distracted during the experiment, didn't listen to instructions, etcetera.

Het commentaar dat je hier aanlevert, wordt alleen naar de admin van het wervingssysteem gestuurd (niet naar de participant). Je kunt het hier melden als de participant bijvoorbeeld niet kwam opdagen zonder je dat te laten weten, of als ze afgeleid waren tijdens het experiment, de instructies niet serieus namen, etcetera.

**Comment by tymees** [comment]
Toegevoegd!
