### ISSUE TITLE
Meldingen kloppen niet bij sluiten/openbaar maken van experimenten (NL)

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#147]
dit blijkt ook in het bestaande systeem al te zitten - de engelstalige meldingen zijn wel goed, maar de nederlandstalige niet:

in het overzicht van experimenten:
https://experimenten-admin.tst.lab.hum.uu.nl/experiments/

als je daar een experiment sluit voor pps, krijg je de melding 'experiment verborgen'. zou moeten zijn 'experiment gesloten voor proefpersonen'.
als je het sluit, krijg je de melding 'Experiment openbaar gemaakt' (-> experiment geopend voor proefpersonen)

als je het experiment verbergt, krijg je 'experiment ge-opent' (-> experiment verborgen)
en als je het openbaar maakt, krijg je 'experiment gesloten'. (-> experiment openbaar gemaakt)

**Comment by tymees** [comment]
Oke geen idee _hoe_ ik die dingen er dubbel fout in heb gezet. Maar de juist vertalingen staan nu bij de juiste vertaal-keys.
