### ISSUE TITLE
groen

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#148]
het maakt verder niet uit ofzo, maar waarom is er van alles groen op de pagina waar je de pp-info kunt aanpassen? 

https://experimenten-admin.tst.lab.hum.uu.nl/participants/3/edit/

**Comment by irisopgithub** [comment]
ook op de pagina waar je een nieuw experiment aanmaakt zijn een paar velden groen. het is vast iets van dat nieuwe template, maar ik snap niet wat het betekent.

**Comment by tymees** [comment]
Eh, dat is de validatie die draait. Alleen, op bestaande entries draait hij ook op de eerste page-load (het is eigenlijk de bedoeling dat die alleen groen worden als je een fout hebt gemaakt ergerns. Het foute veld wordt dan rood, en de rest groen.)

Ik kan het uitzetten indien gewenst?

**Comment by irisopgithub** [comment]
aha! de hele validatie uitzetten lijkt me geen goed idee. als je het uit kunt zetten alleen voor de eerste page-load wel. maar als dat niet kan, dan wennen we er wel aan ;-)
het is vooral verwarrend omdat alleen een bepaald type veld groen wordt. (checkbox bijvoorbeeld niet). maar nogmaals, het maakt niet zoveel uit.

**Comment by tymees** [comment]
Met uitzetten bedoel ik specifiek alleen het uitzetten van het mechanisme dat correcte velden 'groen' maakt. (Dus je krijg nog wel steeds rode velden bij fouten). Ik zou nooit opperen om de hele validatie uit te zetten ;)

**Comment by irisopgithub** [comment]
oh, alleen rood lijkt me prima, ja, graag dat!

**Comment by tymees** [comment]
Ik heb overal waar deze code draaide het uitzet, voor de zekerheid
