### ISSUE TITLE
mail template aanpassen geeft Server Error (500)

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#153]
ik probeerde net in areti's experiment {{ additional_instructions }} te vervangen door de volgende tekst:

Je kunt alleen meedoen met dit experiment als je opgegroeid bent met het Nederlands als moedertaal (meerdere moedertalen is geen bezwaar), als je niet dyslectisch bent, en als je minstens 18 jaar oud bent.
Als je gehoorproblemen hebt, of een aandachtsstoornis (bijvoorbeeld ADD/ADHD), of een taalstoornis (bijvoorbeeld TOS), kun je niet meedoen.

toen kreeg ik een 
Server Error (500)

de wijziging is wel doorgekomen, en ik kan de mail met de gewijzigde tekst ook gewoon versturen.

**Comment by tymees** [comment]
Relevante Sentry log:
https://uu-cdh.sentry.io/issues/6985538/?environment=production&project=4507888741122128&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=0

**Comment by irisopgithub** [comment]
ik kreeg dezelfde error net nog een keer.

**Comment by bbonf** [comment]
Ik heb een fix hiervoor klaar staan, maar ik ga liever verder uitzoeken waarom het maar soms fouts gaat.

**Comment by bbonf** [comment]
Looks like it's working when editing the templates via Experiment detail -> "Edit mail templates" button, but not when using the experiment overview action menu -> "edit mail templates".
Because the first link appends a `?next=...` parameter and the second doesn't.

**Comment by irisopgithub** [comment]
hij geeft nog steeds dezelfde error. (areti wil weer gaan meten voor een oud experiment, dus ik moest de templates aanpassen naar de nieuwe situatie)
