### ISSUE TITLE
telefoonnummer komt niet door in reminder-mail

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#155]
li wees me erop dat het telefoonnummer van de proefleider niet doorkomt in de herinneringsmail. (wel in de bevestigingsmail).

<img width="727" alt="Screenshot 2024-09-16 at 16 30 02" src="https://github.com/user-attachments/assets/4106f15b-4ed6-48bd-bcf4-6af1ed95ca95">

**Comment by irisopgithub** [comment]
li dacht dat het misschien kwam omdat er bij haar telefoonnummer ook het nummer van het lab staat (dat voeg ik altijd toe bij de labs waar bereik een probleem kan zijn en die soundproof cabines hebben). maar ook met alleen haar nummer werkt het niet.

**Comment by irisopgithub** [comment]
ik heb trouwens ook net een half uur geleden een paar honderd uitnodigingen de deur uit gedaan, en vanochtend ook

**Comment by bbonf** [comment]
Het veld is vernoemd naar `leader_phonenumber` ipv `leader_phone`. Ik heb de betrefende template aangepast.

**Comment by irisopgithub** [comment]
dank je! doet-ie het nu dan, of moet-ie eerst nog live gezet worden?

**Comment by bbonf** [comment]
dat is in de applicatie aangepast en niet in de code. als je de "preview email" knop gebruikt zou je de nummer moeten kunnen zien.

**Comment by irisopgithub** [comment]
die knop heb ik niet (reminder sturen doe ik vanuit het pp-overzicht, daar zit niet zo'n knop). maar hij doet het idd, superfijn, dankjewel!
