### ISSUE TITLE
exp verschijnt dubbel in lijst voor tijn, en error bij tijdstippen aanmaken

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#87]
Melding van tijn:

-Het experiment verschijnt 2 keer in het overzicht van mijn experimenten
-Ik kan geen nieuwe timeslots toevoegen omdat ik dan de error krijg:
er is iets fout gegaan
sorry! het lijkt erop dat wij iets fout hebben gedaan aan onze kant! (etc)

Ik kan het repliceren, als ik mezelf onder mijn 'externe proefleider'-account de hoofdproefleider van dit experiment maak (wandelende schooljuffen) verschijnt-ie zelfs drie keer in de lijst, en ik krijg ook de error die tijn krijgt als ik op het tijdstippen-icoontje klik. 

Hoe vaak-ie in de lijst verschijnt, lijkt af te hangen van hoeveel andere proefleiders er zijn (als ik er daar eentje minder heb krijg ik het exp ook maar 2 keer in de lijst te zien).

**Comment by irisopgithub** [comment]
oh ja en marijke had geen probleem, maar die heeft ook geen andere proefleiders aan haar exp hangen

**Comment by tymees** [comment]
Sugt.... 

Code is aangepast om iets intelligenter unieke records op te halen uit de database...

**Comment by irisopgithub** [comment]
jep, is opgelost, tnx!
