### ISSUE TITLE
HTML wordt escaped zonder {link_to_subscribe:"deze link"} in uitnodigingsmail

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#89]
De html wordt niet gerenderd als er geen {link_to_subscribe:"deze link"} in de uitnodigingsmail staat. Ik kwam erachter omdat ik nu toevallig het systeem aan het misbruiken was om mails te sturen over het nieuwe systeem (wat verder wel lukt, ik heb gewoon alleen de code erin gezet en het stukje tekst leeg gelaten).

Voor de exp op locatie is het natuurlijk geen probleem, daar moet gewoon ook altijd een link in. Voor de online exp is het wel een beetje een probleem, daar moet wel altijd een link in, maar niet perse naar een inschrijfpagina.

Ik zou zweren dat ik bij de online exp ooit een veld heb zien staan waar je die link (bijvoorbeeld naar de dataserver) in kon zetten, maar blijkbaar toch niet?

**Comment by tymees** [comment]
Gefixt in de code, maar ik wacht even tot een moment dat het niet zo druk is op de site. (Ik zie een paar mensen rondeuzen op de site)

> Ik zou zweren dat ik bij de online exp ooit een veld heb zien staan waar je die link (bijvoorbeeld naar de dataserver) in kon zetten, maar blijkbaar toch niet?

Die is er niet nee. Ik heb dat scenario wel beschreven, maar met het idee dat je die link gewoon met een HTML hyperlink er in zou zetten. ``<a href=""....`` enzo.

**Comment by irisopgithub** [comment]
> Gefixt in de code, maar ik wacht even tot een moment dat het niet zo druk is op de site voordat ik het live zet. (Ik zie een paar mensen rondeuzen op de site)

tnx!
en het is maar goed dat ik dat niet kan zien, of er mensen rondneuzen, ik zou nooit meer aan werken toekomen. ik ben ooit admin geweest op een forum waar ik vrij veel kon zien van hoe mensen zich in real time gedroegen, echt fascinerend vond ik dat. net een wolk spreeuwen.

**Comment by tymees** [comment]
Nouja hoe ik het zie is niet bepaald makkelijk te lezen, dus je krijgt al snel hoofdpijn :P Ik kijk zelf gewoon naar de frequentie dat ik nieuwe regels zie verschijnen. 

Het was even stil, dus het staat nu online
