### ISSUE TITLE
Uitgesloten experimenten

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#93]
In het experimenten overzicht staat iets wat een teller zou moeten zijn voor uitgesloten experimenten (dus hoeveel er uitgesloten worden).

In plaats daarvan staat er nu een ander getal, ik denk het nummer van 1 van de experimenten die uitgesloten worden.

**Comment by irisopgithub** [comment]
ook dit is totaal niet dringend trouwens, het is meer een idiot-check als ik een nieuw experiment aanmaak

**Comment by tymees** [comment]
Alle counters op die pagina waren een beetje funky, bij de volgende update horen ze te kloppen

> In plaats daarvan staat er nu een ander getal, ik denk het nummer van 1 van de experimenten die uitgesloten worden.

Nee ze zaten wel te tellen wat er bij stond... Echter het telde sommige experimenten dubbel (of driedubbel, of vierdubbel... etc).
Vergelijkbaar probleem als Tijn laatst had
