### ISSUE TITLE
herinneringsmails versturen proefpersonen als leider

### ISSUE THREAD

**Issue by tymees** [UiL-OTS-labs/ppn-backend#96]
From email:

> Ik probeer vanuit het experimentensysteem herinneringsmails te versturen naar de proefpersonen van morgen maar ik krijg een foutmelding (405).
>
> Ik kan me zo voorstellen dan het nu een beetje laat is om dat vandaag nog op te lossen, dus ik zal even handmatig herinneringsmails sturen, maar dan zijn jullie er in ieder geval van op de hoogte.

Apperantly me forgot to implement that specific function :sweat_smile:

**Comment by irisopgithub** [comment]
ik heb dit echt supervaak getest, maar blijkbaar alleen als admin. (note to self: voor het nieuwe babylabsysteem alles in alle rollen testen).

ik weet niet of het handig is als de secundaire proefleider ook reminders kan versturen, - wat is het makkelijkst voor jou?

**Comment by tymees** [comment]
Het makkelijkst is als alle proefleiders hetzelfde behandelen. Dat is wat ik tot nu toe heb gedaan mbt rechten

**Comment by irisopgithub** [comment]
ok, prima! ik documenteer dat dan even in de howto.

**Comment by tymees** [comment]
Het staat nog niet live, dat zal ik later vandaag ergens doen
