### ISSUE TITLE
Taal proefleider

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/ppn-backend#99]
in het oude systeem zat voor proefleiders een variabele of ze engels- of nederlandstalig waren. ik vroeg me af of die er in het nieuwe systeem ook in zit? als ik een proefleider edit of aanmaak zie ik 'm niet staan, en als de proefleider z'n eigen profiel edit ook niet, maar misschien is dat een display-kwestie?

ik vraag het omdat ik panagiota zag worstelen met het nederlands in de interface, ze zei dat ze dat niet kon veranderen. ik ben net even als proefleider ingelogd en je kunt het als proefleider (natuurlijk) wel veranderen, maar dat had ze blijkbaar niet gezien. het is best handig als ik dat voor mensen kan instellen. maar als die variabele er niet meer is moet je 'm niet gaan aanmaken, dan zet ik het in de howto. (het is natuurlijk ook behoorlijk standaard op alle UU-websites).

**Comment by tymees** [comment]
Die variabele is er niet in dit systeem, omdat we leunen op Django's automatische taal-detectie. We kunnen dit wel instelbaar maken in principe, maar liever niet ;)

Het is wel zo dat als iemand's PC in een taal staat die we niet herkennen (we herkennen alleen NL en EN), we automatisch switchen naar NL (omdat dat de standaard taal is). Ik kan deze standaard naar engels zetten, mogelijk dat dat wat helpt? Voor pp zou dit niet veel moeten uitmaken, omdat we die interfaces hardcoded op Nederlands zetten. (Naast het feit dat die _waarschijnlijke_ sowieso de NL versie krijgen door de automatische taal detectie)

**Comment by irisopgithub** [comment]
ok, helder. ik gok dat panagiota haar laptop op grieks heeft staan. ik denk dat de standaard-bij-niet-herkennen op engels zetten een heel goed idee is!

veel nl studenten (die ik zie) hebben de taal wel op engels staan trouwens (godzijdank), maar ik kan zien wat er voor ze gebeurt want dat heb ik ook.

**Comment by tymees** [comment]
Aangepast tijdens de update van net
